export const EErrors = {
  ROUTING_ERROR: 1,
  INVALID_REQUEST: 2,
  INVALID_TOKEN: 3,
  INVALID_PERMISSIONS: 4,
  INVALID_CREDENTIALS: 5,
  CART_NOT_FOUND: 6,
  PRODUCT_NOT_FOUND: 7,
  TICKET_NOT_FOUND: 8,
  USER_NOT_FOUND: 9,
  CART_DAO_ERROR: 10,
  PRODUCT_DAO_ERROR: 11,
};
